# Generated by Django 3.1.4 on 2020-12-16 14:20

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'open'), (1, 'ordered'), (2, 'in_delivery'), (3, 'delivered'), (4, 'cancelled')], default=0),
        ),
    ]
