# Generated by Django 3.1.4 on 2020-12-18 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20201217_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='flavour',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pizzas',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('SMALL', 'small'), ('MEDIUM', 'medium'), ('LARGE', 'large')], max_length=50)),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.pizza')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_pizzas',
            field=models.ManyToManyField(through='orders.OrderItem', to='orders.Pizza'),
        ),
    ]
